config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_in" => "devise/sessions#new"
    get "/users/sign_up" => "devise/registrations#new"
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root 'static_pages#home'
  get '/home' => 'static_pages#home'

  resources :questions
  resources :tests
  resources :test_assignments
  resources :answer_options_assignee_answers, only: [:create]
  resources :assignee_answers

  namespace :users do
    resources :profiles
  end
end

app/models/question.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: questions
#
#  id          :bigint           not null, primary key
#  answer_type :string           not null
#  body        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_questions_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Question < ApplicationRecord
  has_many :questions_tests, dependent: :restrict_with_error
  has_many :tests, through: :questions_tests
  has_many :assignee_answers, dependent: :destroy
  has_many :answer_options, dependent: :destroy

  belongs_to :user

  accepts_nested_attributes_for :answer_options, allow_destroy: true

  SINGLE = 'Single-choice'
  MULTIPLE = 'Multiple-choice'
  TEXT = 'Text'

  enum answer_type: {
    single: SINGLE,
    multiple: MULTIPLE,
    text: TEXT
  }, _prefix: true

  validates :answer_type, presence: true
  validates :body, presence: true
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < BaseController
  before_action :question, only: %i[show edit]

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def show; end

  def create
    if Questions::Create.new(question_params, current_user).call
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if Questions::Update.new(question, question_params).call
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    Questions::Destroy.new(question).call
    if @question.destroy
      flash[:success] = 'Question successfully deleted.'
    else
      flash[:danger] = 'This question cannot be deleted because it is used in Test'
    end
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(
      :body, :answer_type, answer_options_attributes: %i[body]
    )
  end

  def question
    @question ||= Question.find(params[:id])
  end
end

app/views/questions/_form_fields.html.erb
<div class="form-group">
  <%= f.label :body, value: 'Question' %>
  <%= f.text_field :body, class: "form-control mb-20" %>

  <div class='form-group'>
    <select class="form-select mb-20" name='question[answer_type]'>
      <option value="single"><%= Question.answer_types[:single] %></option>
      <option value="multiple"><%= Question.answer_types[:multiple] %></option>
      <option value="text"><%= Question.answer_types[:text] %></option>
    </select>

  <div id='answer-fields'>
    <%= render partial: 'single_answer', locals: { f: f } %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create', class: "btn btn-success btn-sm mt-10", data: {disable_with: 'wait...'} %>
  </div>
</div>

app/views/questions/_navbar_questions.html.erb
<br>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= questions_path %>">Questions</a>
    <div class="text=right">
      <a href="<%= new_question_path %>" class ="btn btn-outline-primary">Add question</a>
    </div>    
  </div>
</nav>
<br>
<div class="container">
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-secondary me-md-2" type="submit">Reset</button>
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</div>

app/views/questions/_preview_questions.html.erb
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th class="u-align-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
    <tr>
      <td><%= question.body %></td>
      <td><%= question.answer_type %></td>
      <td class="u-align-center">
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <a href="<%= question_path(question) %>" class="btn btn-outline-info">Show</a>
          <a href="<%= edit_question_path(question) %>" class="btn btn-outline-secondary">Edit</a>
          <a data-confirm="Are you sure?" data-method="delete" href="<%= question_path(question) %>" class="btn btn-outline-danger">Delete</a>  
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/_single_answer.html.erb
<%= f.fields_for 'answer_options_attributes[]', @question.answer_options.build do |answer| %>

  <p> Your answer </p>
  
  <div class="form-group" id="answer-input">
      <%= answer.text_field 'body',
                        class: "form-control mt-10",
                        placeholder: 'Your answer',
                        autofocus: true %>
  </div>

  <div id="dynamic-inputs"></div>

  <%= button_tag "Add one more answer", type: 'button', id: 'add-new-answer', class: 'btn btn-primary mt-10' %>
  <%= button_tag "Remove answer", type: 'button', id: 'remove-answer', class: 'btn btn-danger mt-10' %>
<% end %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>

<header>
  <%= render 'navbar_questions' %>
</header>
<br>
<body>
  <%= render 'preview_questions' %>
  <br>
</body>
<footer>
  <div class="pagination justify-content-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
</footer>

app/views/questions/new.html.erb
<% provide :page_title, 'New Question' %>

<h3 class='inline-block'>New question</h3> 
<a href="<%= questions_path %>", class="btn btn-secondary back-button">Back</a>

<div class="mt-40">
  <%= form_for(@question, html: {role: "form"}) do |form|%>
    <%= render partial: 'form_fields', locals: {f: form} %>
  <% end %>
</div>

app/views/questions/show.html.erb
<% provide :page_title, 'Question' %>
<br>
<div class="container">
  <h1><%= @question.body %></h1>

  <h3>Type Question: <%= @question.answer_type %></h3>
  <br>
  <ul class="list-group list-group-flush">
      <% @question.answer_options.each do |answer| %>
      <li class="list-group-item list-group-item">
        <%= answer.body %>
      </li>
      <% end %>
  </ul>
</div>