config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_in" => "devise/sessions#new"
    get "/users/sign_up" => "devise/registrations#new"
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root 'static_pages#home'
  get '/home' => 'static_pages#home'

  resources :questions
  resources :tests
  resources :test_assignments
  resources :answer_options_assignee_answers, only: [:create]
  resources :assignee_answers

  namespace :users do
    resources :profiles
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  unconfirmed_email      :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  after_create :build_users_profile
  after_update :send_password_change_email, if: :needs_password_change_email?

  has_many :questions, dependent: :nullify
  has_many :tests, dependent: :nullify
  has_one :user_profile, dependent: :destroy, class_name: 'Users::Profile'

  def needs_password_change_email?
    encrypted_password_changed? && persisted?
  end

  def send_password_change_email
    UserMailer.password_changed(id).deliver
  end

  def build_users_profile
    Users::Profile.create(user: self)
  end
end

app/models/users/assignee_answer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assignee_answers
#
#  id                 :bigint           not null, primary key
#  body               :text
#  value              :integer
#  answer_option_id   :integer
#  question_id        :bigint
#  test_assignment_id :bigint
#
# Indexes
#
#  index_assignee_answers_on_question_id         (question_id)
#  index_assignee_answers_on_test_assignment_id  (test_assignment_id)
#
# Foreign Keys
#
#  fk_rails_...  (question_id => questions.id)
#  fk_rails_...  (test_assignment_id => test_assignments.id)
#
class TestAssignment < ApplicationRecord
  belongs_to :test_assignment
  belongs_to :question
end

app/models/users/profile.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users_profiles
#
#  id         :bigint           not null, primary key
#  first_name :string           default(""), not null
#  last_name  :string           default(""), not null
#  user_id    :bigint
#
# Indexes
#
#  index_users_profiles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
module Users
  class Profile < ApplicationRecord
    self.table_name_prefix = 'users_'

    belongs_to :user
  end
end

app/controllers/users/profiles_controller.rb
# frozen_string_literal: true

module Users
  class ProfilesController < BaseController
    before_action :set_users_profile
    before_action :authenticate_user!

    def update
      Users::Update.new(@users_profile, users_profile_params).call
      render :show
    end

    private

    def set_users_profile
      @users_profile = Users::Profile.find_by(user_id: params[:id])
    end

    def users_profile_params
      params.require(:users_profile).permit(:id, :first_name, :last_name, :user_id)
    end
  end
end

app/views/users/profiles/edit.html.erb
<div class="container">
  <h1>Update my profile</h1>
</div>

<%= form_for :users_profile, url: users_profile_path, method: :patch do |f| %>
    <div class="form-group">
      First name: <%= f.text_field :first_name %>
      Last name : <%= f.text_field :last_name %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save', class: "btn btn-primary save-button" %>
    </div>
<% end %>

app/views/users/profiles/show.html.erb
<div class="container">
  <a href="<%= '/home' %>", class="btn btn-secondary back-button">Back</a>
  <h1>My profile</h1>
</div>

<div class="form-group font_size">
  First name: <%= @users_profile.first_name %><br />
  Last Name: <%= @users_profile.last_name %>
</div>

<%= link_to "Edit profile data", edit_users_profile_path, class: "btn btn-primary btn-sm mt-10", method: :get %>
<%= link_to 'Change email and password', edit_user_registration_path, class: "btn btn-primary btn-sm mt-10" %>