config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_in" => "devise/sessions#new"
    get "/users/sign_up" => "devise/registrations#new"
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root 'static_pages#home'
  get '/home' => 'static_pages#home'

  resources :questions
  resources :tests
  resources :test_assignments
  resources :answer_options_assignee_answers, only: [:create]
  resources :assignee_answers

  namespace :users do
    resources :profiles
  end
end

app/models/test_assignment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: test_assignments
#
#  id              :bigint           not null, primary key
#  assignee_email  :string           not null
#  expiration_time :string           not null
#  status          :string           default("sent")
#  test_id         :bigint
#
# Indexes
#
#  index_test_assignments_on_test_id  (test_id)
#
# Foreign Keys
#
#  fk_rails_...  (test_id => tests.id)
#
class TestAssignment < ApplicationRecord
  belongs_to :test
  has_many :assignee_answers, dependent: :destroy

  validates :assignee_email, presence: true
  validates :expiration_time, presence: true

  enum status: {
    sent: 'sent',
    in_progress: 'in_progress',
    waiting_for_review: 'waiting_for_review',
    reviewed: 'reviewed'
  }
end

app/controllers/test_assignments_controller.rb
# frozen_string_literal: true

class TestAssignmentsController < BaseController
  helper_method :tests, :test_assignment, :questions

  LIST_LAST_USERS = 20

  def index
    @pagy, @test_assignments = pagy(test_assignments)
  end

  def show; end

  def new
    @test_assignment = TestAssignment.new
  end

  def create
    test_assignment = TestAssignments::Create.new(test_assignment_params).call
    TestAssignmentMailer.test_assignment_email(test_assignment.id).deliver
    redirect_to test_assignments_path
  end

  private

  def test_assignment_params
    params.require(:test_assignment).permit(:assignee_email, :expiration_time, :test_id)
  end

  def test_assignments
    TestAssignment.includes(:test)
                  .where(tests: { user_id: current_user.id })
  end

  def tests
    @tests ||= Test.where(user_id: current_user.id).last(LIST_LAST_USERS)
  end

  def test_assignment
    @test_assignment ||= TestAssignment.find(params[:id])
  end

  def questions
    @questions ||= test_assignment.test.questions.includes(:answer_options)
  end
end

app/views/test_assignments/_form_fields.html.erb
<div class="form-group">
  <div>
    <%= f.label :assignee_email, value: 'Assignee email' %>
    <%= f.email_field :assignee_email, class: "form-control mb-20" %>
  </div>

  <select class="form-select mb-20", name='test_assignment[test_id]'>
    <%= f.label :test_id, value: 'Select test' %>
    <% tests.each do |test| %>
      <option value="<%= test.id %>"><%= test.name %></option>
    <% end %>
  </select>

  <%= f.label :expiration_time, value: 'Expiration time' %>
  <p><%= f.datetime_field :expiration_time, value: @test_assignment.expiration_time %></p>

  <div class="form-group">
    <%= f.submit 'Assign', class: "btn btn-success btn-sm mt-10", data: {disable_with: 'wait...'} %>
  </div>
</div>

app/views/test_assignments/_navbar_test_assignments.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= test_assignments_path %>">Test asssignments</a>
    <div class="text=right">
      <a href="<%= new_test_assignment_path %>" class ="btn btn-outline-primary new-button">Create new test assignment</a>
    </div>    
  </div>
</nav>

app/views/test_assignments/_table.html.erb
<%= render partial: 'navbar_test_assignments' %>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Test name</th>
      <th>Student email</th>
      <th>Status</th>
      <th>Sent link</th>
      <th>Expiration time</th>
      <th>Student`s answers</th>
    </tr>
  </thead>
  <tbody>
    <% test_assignments.each do |test_assignment| %>
    <tr>
      <td><%= test_assignment.test.name %></td>
      <td><%= test_assignment.assignee_email %></td>
      <td><%= test_assignment.status %></td>
      <td><a href="<%= test_assignment_path(id: test_assignment.id) %>" class="btn btn-outline-info">Test</a></td>
      <td><%= test_assignment.expiration_time %></td>
      <td><a href="<%= assignee_answers_path(id: test_assignment.id) %>" class="btn btn-outline-info">Student`s answers</a></td>
    </tr>
    <% end %>
  </tbody>
</table>

<footer>
  <div class="pagination justify-content-center">
    <%== pagy_bootstrap_nav @pagy %>
   </div>
</footer>

app/views/test_assignments/index.html.erb
<% provide :page_title, 'Test Assignments' %>
<br>
<%= render partial: 'table', locals: {test_assignments: @test_assignments} %>

app/views/test_assignments/new.html.erb
<% provide :page_title, 'New Test Assignment' %>

<h3 class='inline-block'>New test assignment</h3>

<div class="mt-40">
  <%= form_for(@test_assignment, url: test_assignments_path, html: {role: "form"}) do |form|%>
    <%= render partial: 'form_fields', locals: {f: form} %>
  <% end %>
</div>

app/views/test_assignments/show.html.erb
<% provide :page_title, 'Test Assignment' %>

<div class="container text-center">  
  <h1><%= test_assignment.test.name %></h1>
  <br>
</div>


<div class="form-group">
  <%= form_for(:assignee_answer,
                url: answer_options_assignee_answers_path,
                method: :post,
                html: { role: 'form'}) do |f| %>
    <%= f.hidden_field :test_assignment_id, :value => test_assignment.id %>
    <% questions.each do |question| %><br>
      <h4>
        <% if question.answer_type_single? %>
          <div class="form-group">
            <%= question.body %>
            <% question.answer_options.each do |answer_option| %>
              <div class="block">
                <%= f.radio_button "#{question.id}[#{answer_option.id}][value]", answer_option.correct?, {id: "assignment_result_value_#{answer_option.id}"} %>
                <label for="<%= "assignment_result_value_#{answer_option.id}" %>"><%= answer_option.body %></label>
              </div> 
            <% end %>
          </div>   
        <% elsif question.answer_type_multiple? %>
          <div class="form-group">
            <%= question.body %>
            <% question.answer_options.each do |answer_option| %>
              <div class="block">
                <%= f.check_box :value, 
                                name: "assignee_answer[#{question.id}][#{answer_option.id}][value]", 
                                id: "assignee_answer_value_#{answer_option.id}" %>
                <label for="<%= "assignee_answer_value_#{answer_option.id}" %>"><%= answer_option.body %></label>
              </div> 
            <% end %>
          </div>  
        <% else %>
          <%= fields_for "assignee_answer[#{question.id}]" do |ff| %>
            <div class="form-group">
              <label for="<%= "answer_#{question.id}" %>"><%= question.body %></label>
              <%= ff.text_area(:body, id: "answer_#{question.id}") %>
            </div>
          <% end %>
        <% end %>
      </h4>
    <% end %>

    <div  class="form-group">
      <%= f.submit 'Submit', class: "btn btn-success bn-sm mt-10", data: {disable_with: 'wait...'} %>
    </div>
  <% end %>
</div>