config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_in" => "devise/sessions#new"
    get "/users/sign_up" => "devise/registrations#new"
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root 'static_pages#home'
  get '/home' => 'static_pages#home'

  resources :questions
  resources :tests
  resources :test_assignments
  resources :answer_options_assignee_answers, only: [:create]
  resources :assignee_answers

  namespace :users do
    resources :profiles
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="nav navbar navbar-expand-lg navbar-light bg-light container-fluid">
        <div class="container">
          <a class="navbar-brand" href="<%= root_path %>">
            <img src="<%= asset_path('logo2.jpeg') %>" width="30" height="24" class="d-inline-block align-text-top">
            Easy Check
          </a>
          <% if user_signed_in? %>
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="<%= test_assignments_path %>">Test Assignments</a>
              <a class="nav-item nav-link" href="<%= tests_path %>">Tests</a>
              <a class="nav-item nav-link" href="<%= questions_path %>">Questions</a>
            </div>
            <ul class="navbar-nav navbar-right">
                <li>
                  <a class="nav-link" href="<%= destroy_user_session_path %>">Log Out</a>
                </li>
            </ul>
          <% else %>
            <ul class="navbar-nav navbar-right">
                <li class="nav-item ">
                  <a class="nav-link" href="<%= new_user_session_path %>">Sign in</a>
                </li>
                <li>
                  <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                </li>
            </ul>
          <% end %>
        </div>
      </nav>
      <br>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% flash.each do |k, v| %>
          <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>
      <%= yield %>
    </div>
    <br>
    <footer class="footer">
      <div class="container-fluid bg-light">
        all rights reserved 2021
      </div>
    </footer>
  </body>
</html>

app/views/layouts/bootstrap-mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  <%= stylesheet_link_tag "application-mailer", media: "all" %>
  </head>

  <body class="bg-light">
    <%= yield %>
  </body>
</html>

app/views/layouts/test_assignment_mailer.text.erb
<%= yield %>